### ISSUE TITLE
argument passed to callback is string rather than array

### ISSUE THREAD

**Issue by vinay-webrmedia** [10up/WP-Minions#31] opened 2017-09-18 08:40 UTC
I tried the example given in the ``Readme`` but my callback method received a string `myvalue` rather than an array `array('mykey' => 'myvalue'`).

Output : 
![image](https://user-images.githubusercontent.com/18738048/30534359-7d30bc58-9c7b-11e7-951d-8c8dfe6fa14b.png)

I am using ``Gearman``.
Wordpress version ``4.8.1``

**Comment by cmmarslender** [comment] 2017-09-25 20:35
@vinay-webrmedia  Aside from Gearman and WP 4.8.1, what else can you tell me about the environment this is running in? Is this a local or remote environment? If local, what are you using for dev? VVV?

I'm unable to reproduce in my dev environment.

**Comment by barryceelen** [comment] 2018-07-04 13:17
I ran into the same problem and passing `array( array( 'mykey' => 'myvalue' ) )` in stead of `array( 'mykey' => 'myvalue' )` did the trick, oddly...

**Comment by cmmarslender** [comment] 2018-07-06 21:04
This seems to have happened when falling back from an async task queue like RabbitMQ or Gearman to the wp cron implementation. Resolved in #32

Please reopen this issue if you see it with that change.

**Closed as completed by cmmarslender** 2018-07-06 21:04 UTC

**Comment by barryceelen** [comment] 2018-07-06 21:28
Thanks @cmmarslender!
